add Google Analytics
purduesigbots/pros-vsc pull request #16
Opened 2021-06-17 20:49 UTC by baylessj

Closes #13.

Posts analytics info to the VSCode Google Analytics property in the SIGBots account (UA-84548828-7).

2021-06-17 21:28 UTC, kunwarsahni01 requested changes
Want to have most actions tracked. Adding pageviews is great as well. LGTM

2021-06-17 21:28 UTC, kunwarsahni01 commented on src/extension.ts
> +    analytics.sendAction("build");
```suggestion
    analytics.sendAction("upload&build");
```

2021-06-17 21:28 UTC, kunwarsahni01 commented on src/extension.ts
>    vscode.commands.registerCommand("pros.upload", upload);
```suggestion
  vscode.commands.registerCommand("pros.upload", () => {
    analytics.sendAction("upload");
    upload();
  });
```

2021-06-17 21:28 UTC, kunwarsahni01 commented on src/extension.ts
>    vscode.commands.registerCommand("pros.upgrade", upgradeProject);
```suggestion
  vscode.commands.registerCommand("pros.upgrade", () => {
    analytics.sendAction("upgrade");
    upgradeProject();
  });
```

2021-06-20 14:36 UTC, baylessj commented
@kunwarsahni01 This PR should be ready for a re-review from you whenever you get a chance :smile:

2021-06-20 14:37 UTC, kunwarsahni01 approved these changes
LGTM

2021-06-20 14:38 UTC, merged